export const UPDATE_APP_INFO = 'UPDATE_APP_INFO'
export const UPDATE_APP_NAME = 'UPDATE_APP_NAME'
export const UPDATE_BASE_URL = 'UPDATE_BASE_URL'
export const UPDATE_APP_VERSION = 'UPDATE_APP_VERSION'
